"""
Generating the Luanti-side files: the world, the server configuration and the mod.

Everything a beginner gets wrong by hand is written here instead: the mod is placed in
``worldmods/``, which Luanti loads without any entry in ``world.mt`` and without a
checkbox in the main menu, and the ``miney`` privilege is granted through
``default_privs`` so the bot has it the first time it connects.
"""
from __future__ import annotations

import getpass
import hashlib
import re
import secrets
import shutil
from pathlib import Path
from typing import Callable

#: Game used unless another one is asked for. Every example in our documentation uses
#: its node names, so changing this default would break them.
DEFAULT_GAME = "minetest_game"

#: Privileges every player gets. "miney" is what lets the bot run Lua.
DEFAULT_PRIVS = ("interact", "shout", "miney")

#: Luanti rejects names outside this set.
_ALLOWED_NAME_CHARS = re.compile(r"[^A-Za-z0-9_-]")

#: Luanti's player name length limit.
_MAX_NAME_LENGTH = 20


def write_world_mt(world_dir: Path, gameid: str) -> None:
    """
    Write a world's ``world.mt``.

    :param world_dir: The world directory. Created if it does not exist.
    :param gameid: The game to record. It cannot be changed later without a new world.
    """
    world_dir.mkdir(parents=True, exist_ok=True)
    (world_dir / "world.mt").write_text(
        "\n".join(
            [
                "# Generated by miney. Edit at your own risk.",
                f"gameid = {gameid}",
                "backend = sqlite3",
                "player_backend = sqlite3",
                "auth_backend = sqlite3",
                "mod_storage_backend = sqlite3",
                "creative_mode = false",
                "enable_damage = true",
                "",
            ]
        ),
        encoding="utf-8",
    )


def read_world_gameid(world_dir: Path) -> str | None:
    """
    Read which game a world was created with.

    :param world_dir: The world directory.
    :return: The game id, or None if the world does not exist yet or records no game.
    """
    world_mt = world_dir / "world.mt"
    try:
        text = world_mt.read_text(encoding="utf-8")
    except OSError:
        return None
    for line in text.splitlines():
        if line.strip().startswith("gameid"):
            _, _, value = line.partition("=")
            value = value.strip()
            if value:
                return value
    return None


def write_config(config_file: Path) -> None:
    """
    Write the shared ``luanti.conf``.

    The port is deliberately not written here. It belongs to a single world and lives in
    that world's state, so there is only ever one source of truth for it.

    :param config_file: Target file. Parent directories are created.
    """
    config_file.parent.mkdir(parents=True, exist_ok=True)
    config_file.write_text(
        "\n".join(
            [
                "# Generated by miney. Edit at your own risk.",
                f"default_privs = {', '.join(DEFAULT_PRIVS)}",
                # Bind the server to loopback only. Its whole audience is on this machine
                # - the learner's own client and Miney's bot both connect to 127.0.0.1 -
                # so there is nothing to gain from listening on every interface, and two
                # things to lose: Windows pops up a firewall dialog the first time a
                # process binds 0.0.0.0, and an open port on a school or home network is
                # an exposure a learning server has no reason to carry.
                "bind_address = 127.0.0.1",
                "enable_rollback_recording = false",
                "server_announce = false",
                "enable_remote_media_server = false",
                "",
            ]
        ),
        encoding="utf-8",
    )


def derive_player_name(raw: str, reserved: str = "miney") -> str:
    """
    Turn an operating system user name into something Luanti accepts.

    :param raw: The name to start from.
    :param reserved: A name that must not be produced, because the bot uses it.
    :return: A usable player name. Falls back to "player" when nothing usable remains.
    """
    cleaned = _ALLOWED_NAME_CHARS.sub("", raw)[:_MAX_NAME_LENGTH]
    if not cleaned:
        cleaned = "player"
    if cleaned.lower() == reserved.lower():
        cleaned = f"{cleaned}1"
    return cleaned


def current_player_name() -> str:
    """
    The player name for this machine's user.

    :return: A usable player name derived from the operating system user.
    """
    try:
        raw = getpass.getuser()
    except Exception:  # getpass raises bare Exception when it cannot determine a user
        raw = ""
    return derive_player_name(raw)


def ensure_client_password(
    client_pw: Path, generator: Callable[[], str] | None = None
) -> str:
    """
    Read the learner's client password, generating one on first use.

    Written without a trailing newline, because Luanti's ``--password-file`` takes the
    file contents verbatim.

    :param client_pw: The password file.
    :param generator: Substitutable password source, for testing.
    :return: The password.
    """
    if client_pw.is_file():
        return client_pw.read_text(encoding="utf-8")
    make = generator or (lambda: secrets.token_urlsafe(16))
    password = make()
    client_pw.parent.mkdir(parents=True, exist_ok=True)
    client_pw.write_text(password, encoding="utf-8", newline="")
    return password


def install_mod(world_dir: Path, mod_source: Path) -> Path:
    """
    Place the Miney mod into a world's ``worldmods``.

    Luanti loads everything in ``worldmods`` unconditionally, so this replaces both the
    "enable the mod" checkbox and any ``load_mod_miney`` line.

    :param world_dir: The world directory.
    :param mod_source: Directory holding the mod, containing ``mod.conf``.
    :return: The directory the mod was installed into.
    """
    target = world_dir / "worldmods" / "miney"
    if target.exists():
        shutil.rmtree(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(mod_source, target)
    return target


def mod_fingerprint(directory: Path) -> str:
    """
    A content fingerprint of a mod directory, for telling two copies apart.

    Used to decide whether an installed mod still matches the one shipped with this
    Miney, so that :func:`install_mod` runs when the package was upgraded and stays
    out of the way otherwise. The mod's ``mod.conf`` carries no version number, so
    only the file contents can answer that question; modification times cannot,
    because installing the package rewrites them.

    :param directory: The mod directory to fingerprint.
    :return: A hex digest over every file's path and contents, or an empty string if
        the directory does not exist. Unreadable files make the fingerprint differ
        from any other, so a half-copied mod is refreshed rather than trusted.
    """
    if not directory.is_dir():
        return ""
    digest = hashlib.sha256()
    for path in sorted(p for p in directory.rglob("*") if p.is_file()):
        digest.update(path.relative_to(directory).as_posix().encode("utf-8"))
        digest.update(b"\0")
        try:
            digest.update(path.read_bytes())
        except OSError:
            digest.update(hashlib.sha256(str(path).encode("utf-8")).digest())
        digest.update(b"\0")
    return digest.hexdigest()
